version: '3.7'

services:
  waterbot:
    build: .
    environment:
      CRON: '0 0 9 * * * *'
      TIMEZONE: America/New_York
      CEILING_THRESHOLD: 0.2
      FLOOR_THRESHOLD: 3.0
      LAKE_NAME: 'redacted'
      FULL_POOL_URL: 'redacted'
      CURRENT_POOL_URL: 'redacted'
      PING_URL: 'redacted'
      MAIL_FROM: 'redacted'
      MAIL_TO: 'redacted'
      SENDGRID_API_KEY: 'redacted'
